import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth scroll-pt-[40px] snap-start" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <title>Charlie Bacis Social Media and Graphic Designer</title>
        
      <div className="relative">  
        <Image
          src="/header.svg"
          alt="charlie-header"
          className="w-screen"
          width={200}
          height={200}
        />
       
        <div className="absolute flex items-center justify-center pb-6 bottom-0 w-full z-10 text-white">
           <p>Social Media and Graphic Designer</p>
        </div>

      </div>
  
      <div className="sticky top-0 z-10">  
       <div className="bg-[#124b44] flex justify-around text-white py-2">
        <Link href={"#services"}> Services</Link>
        <Link href={"#history"}> History</Link>
        <Link href={"#portfolio"}> Portfolio</Link>
        <Link href={"#suscribe"}> Suscribe</Link>   
       </div>
      </div>

        {children}
      </body>

      

        

    </html>
  );
}
